In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('./data/ch1_sport_test.csv', index_col='生徒番号')

ｄｆ

学年    握力  上体起こし  点数  順位
生徒番号                         
1      1  40.2     34  15   4
2      1  34.2     14   7  10
3      1  28.8     27  11   7
4      2  39.0     27  14   5
5      2  50.9     32  17   2
6      2  36.5     20   9   9
7      3  36.6     31  13   6
8      3  49.2     37  18   1
9      3  26.0     28  10   8
10     3  47.4     32  16   3

In [4]:
df['握力']

生徒番号
1     40.2
2     34.2
3     28.8
4     39.0
5     50.9
6     36.5
7     36.6
8     49.2
9     26.0
10    47.4
Name: 握力, dtype: float64

In [5]:
df.shape

(10, 5)

In [6]:
import numpy as np
import pandas as pd

#Jupyter Notebookの出力を小数点以下3桁に抑える
%precision 3

#Dataframeの出力を小数点以下3桁の抑える
pd.set_option('precision', 3)

In [7]:
df = pd.read_csv('./data/ch2_scores_em.csv', index_col='生徒番号')

#dfの最初の5行を表示
df.head()

英語  数学
生徒番号        
1     42  65
2     69  80
3     56  63
4     41  63
5     57  76

In [8]:
scores = np.array(df['英語'])[:10]
scores


array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58])

In [9]:
scores_df = pd.DataFrame({'点数':scores}, index = pd.Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], name = '生徒'))
scores_df

点数
生徒    
A   42
B   69
C   56
D   41
E   57
F   48
G   65
H   49
I   65
J   58

In [10]:
sum(scores) / len(scores)

55.0

In [11]:
np.mean(scores)

55.0

In [12]:
scores_df.mean()

点数    55.0
dtype: float64

In [13]:
sorted_scores = np.sort(scores)
sorted_scores

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69])

In [14]:
n = len(sorted_scores)
if n % 2 == 0:
    m0 = sorted_scores[n//2-1]
    m1 = sorted_scores[n//2]
    median = (m0 + m1) / 2
else:
    median = sorted_scores[(n+1)//2 - 1]
    
median
    

56.5

In [15]:
np.median(scores)

56.5

In [16]:
scores_df.median()

点数    56.5
dtype: float64

In [17]:
pd.Series([1,1,1,2,2,3]).mode()

0    1
dtype: int64

In [18]:
pd.Series([1,2,3,4,5]).mode()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [19]:
mean = np.mean(scores)
deviation = scores - mean
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [20]:
another_scores = [50, 60, 58, 54, 51, 56, 57, 53, 52, 59]
another_mean = np.mean(another_scores)
another_deviation = another_scores - another_mean
another_deviation

array([-5.,  5.,  3., -1., -4.,  1.,  2., -2., -3.,  4.])

In [21]:
np.mean(deviation)

0.0

In [23]:
summary_df = scores_df.copy()
summary_df['偏差'] = deviation
summary_df

点数    偏差
生徒          
A   42 -13.0
B   69  14.0
C   56   1.0
D   41 -14.0
E   57   2.0
F   48  -7.0
G   65  10.0
H   49  -6.0
I   65  10.0
J   58   3.0

In [24]:
summary_df.mean()

点数    55.0
偏差     0.0
dtype: float64

In [25]:
np.mean(deviation ** 2)

86.0

In [26]:
np.var(scores)

86.0

In [27]:
scores_df.var()

点数    95.556
dtype: float64

In [31]:
summary_df['偏差二乗']=np.square(deviation)
summary_df


点数    偏差   偏差二乗
生徒                 
A   42 -13.0  169.0
B   69  14.0  196.0
C   56   1.0    1.0
D   41 -14.0  196.0
E   57   2.0    4.0
F   48  -7.0   49.0
G   65  10.0  100.0
H   49  -6.0   36.0
I   65  10.0  100.0
J   58   3.0    9.0

In [32]:
summary_df.mean()

点数      55.0
偏差       0.0
偏差二乗    86.0
dtype: float64

In [33]:
np.sqrt(np.var(scores, ddof=0))

9.273618495495704

In [34]:
np.std(scores, ddof=0)

9.273618495495704

In [35]:
np.max(scores) - np.min(scores)

28

In [37]:
scores_Q1 = np.percentile(scores, 25)
scores_Q3 = np.percentile(scores, 75)
scores_IQR = scores_Q3 - scores_Q1
scores_IQR

15.0

In [ ]:
pd.Series(scores).desc